# Generated by Django 4.1.1 on 2022-09-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_rating_user_alter_rating_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[("Men", "Men"), ("Women", "Women")], default=1, max_length=100
            ),
            preserve_default=False,
        ),
    ]
